# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Academatica' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'CalendarHeatmap'
  pod 'Alamofire', '~> 5.5'
  pod 'lottie-ios'

end
